---
name: Submodule Updates

#############################
# Start the job on all push #
#############################
on:
  # push:
    # branches: [main]
    # paths:
    #   - 'scripts/**'
    #   - 'tools/**'
      
###############
# Set the Job #
###############
jobs:
  build:
    name: Submodule update
    strategy:
      matrix:
        targets: [orange-cloudavenue/terraform-provider-cloudavenue, orange-cloudavenue/cloudavenue-sdk-go, orange-cloudavenue/cloudavenue-cli]
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: ${{ matrix.targets }}
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'orange-cloudavenue'

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.RWORANGECLOUDAVENUE }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}